# Generated by Django 5.0.2 on 2025-05-07 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlisting',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_listings', to='properties.property'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentlisting',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='agents.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentcontact',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='agents.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentavailability',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='agents.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentachievement',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='agents.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentreview',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agents.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentspecialization',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='agents.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentspecialization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertycategory'),
        ),
        migrations.AlterUniqueTogether(
            name='agentlisting',
            unique_together={('agent', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='agentspecialization',
            unique_together={('agent', 'category')},
        ),
    ]
