# Generated by Django 5.2.1 on 2025-05-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertycategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
