# Generated by Django 5.2.1 on 2025-05-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
