# Generated by Django 5.2.1 on 2025-06-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_default_categories'),
        ('properties', '0007_alter_property_bathrooms'),
    ]

    operations = [
    ]
