# Generated by Django 4.2.10 on 2025-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_merge_20250601_1813"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="neighbourhood",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.PositiveIntegerField(help_text="Area in square Meter"),
        ),
    ]
