# Generated by Django 4.2.10 on 2025-07-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_alter_property_neighbourhood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="neighbourhood",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of neighbourhoods"
            ),
        ),
    ]
