# Generated by Django 4.2.10 on 2025-07-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_alter_property_neighbourhood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="neighbourhood",
            field=models.CharField(
                choices=[
                    ("ANAND_LOK", "Anand Lok"),
                    ("ANAND_NIKETAN", "Anand Niketan"),
                    ("ASOLA", "Asola"),
                    ("BANDH_ROAD", "Bandh Road"),
                    ("BIJWASAN", "Bijwasan"),
                    ("CR_PARK", "C.R Park"),
                    ("CHANAKYAPURI", "Chanakyapuri"),
                    ("CHANDAN_HOLA", "Chandan Hola"),
                    ("CHATTARPUR", "Chattarpur"),
                    ("DEFENCE_COLONY", "Defence Colony"),
                    ("DERA_MANDI", "Dera Mandi"),
                    ("DLF_PHASE_1", "DLF Phase -1"),
                    ("FATEHPUR_BERI", "Fatehpur Beri"),
                    ("GK_2", "G.K 2"),
                    ("GK_1", "G.K-1"),
                    ("GADAIPUR", "Gadaipur"),
                    ("GHITORNI", "Ghitorni"),
                    ("GOLF_LINKS", "Golf Links"),
                    ("GREEN_PARK_EXTENSION", "Green Park Extension"),
                    ("GREEN_PARK_MAIN", "Green Park Main"),
                    ("GULMOHAR_PARK", "Gulmohar Park"),
                    ("HAUZ_KHAS", "Hauz Khas"),
                    ("JANGPURA", "Jangpura"),
                    ("JANGPURA_EXTENSION", "Jangpura Extension"),
                    ("JOR_BAGH", "Jor Bagh"),
                    ("KAPASHERA", "Kapashera"),
                    ("LAJPAT_NAGAR", "Lajpat Nagar"),
                    ("MANDI_ROAD", "Mandi Road"),
                    ("MAYFAIR_GARDEN", "Mayfair Garden"),
                    ("NEETI_BAGH", "Neeti Bagh"),
                    ("NIZAMUDDIN_EAST", "Nizamuddin East"),
                    ("NIZAMUDDIN_WEST", "Nizamuddin West"),
                    ("PANCHSHEEL_PARK", "Panchsheel Park"),
                    ("PANSHEEL_ENCLAVE", "Pansheel Enclave"),
                    ("PUSHPANJALI", "Pushpanjali"),
                    ("RADHEY_MOHAN_DRIVE", "Radhey Mohan Drive"),
                    ("SAFDARJUNG_ENCLAVE", "Safdarjung Enclave"),
                    ("SARVODAYA_ENCLAVE", "Sarvodaya Enclave"),
                    ("SATBARI", "Satbari"),
                    ("SDA", "SDA"),
                    ("SHANTI_NIKETAN", "Shanti Niketan"),
                    ("SULTANPUR", "Sultanpur"),
                    ("SUNDAR_NAGAR", "Sundar Nagar"),
                    ("VASANT_KUNJ_FARMS", "Vasant Kunj Farms"),
                    ("VASANT_VIHAR", "Vasant Vihar"),
                    ("WESTEND", "Westend"),
                    ("WESTEND_GREENS", "Westend Greens"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
